Upgrade to Node16 and update dependencies
parallelsystems/clippy-check pull request #4
Opened 2022-11-30 00:53 UTC by gbhand

# Background

GitHub Actions is deprecating Node12 https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

# Description

This PR upgrades the action to use Node16, along with updating dependencies. In order to upgrade to Node16, error handling had to be changed from
```typescript
} catch (error) {
```

to

```typescript
} catch (error: any) {
```

as `catch` blocks now are type annotated (https://github.com/microsoft/TypeScript/issues/36775)

# Verification

Passes local tests

2022-11-30 00:54 UTC, joshparallel approved these changes
LGTM!

2022-11-30 14:42 UTC, klimburg approved these changes

2022-11-30 17:37 UTC, klimburg requested changes
looks like there is an issue when you actually used this branch in monorail

https://github.com/parallelsystems/monorail/actions/runs/3579495678

<img width="914" alt="image" src="https://user-images.githubusercontent.com/6772276/204868646-979fa14e-d33c-485d-bb0d-8583f3e17634.png">

2022-12-05 23:38 UTC, gbhand commented
@klimburg looks like this is unfortunately the expected behavior: 
["Due to token permissions, this Action WILL NOT be able to post clippy annotations for Pull Requests from the forked repositories"](https://github.com/actions-rs/clippy-check#:~:text=Due%20to%20token%20permissions%2C%20this%20Action%20WILL%20NOT%20be%20able%20to%20post%20clippy%20annotations%20for%20Pull%20Requests%20from%20the%20forked%20repositories.)

[Pull requests from forks cannot create Checks due to security exposure](https://github.com/actions-rs/clippy-check/issues/2#issuecomment-538663011). 

Besides this error (which should no longer occur once merged to master) the rest of the output looks successful. Is that sufficient to get this merged?

2022-12-05 23:44 UTC, klimburg approved these changes

2022-12-05 23:45 UTC, merged